spring:
  application:
    name: registry-service

server:
  port: 8070

eureka:
  instance:
    hostname: 3.125.175.99
    port: ${server.port}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
